#pragma once

// generated by the columns. DO NOT EDIT!


#ifdef __cplusplus
extern "C" {
#endif
struct clColumn;

extern const struct clColumn stUseItemReqObject[];
extern const struct clColumn stDropObject[];
extern const struct clColumn stUseItemRspObject[];
#ifdef __cplusplus
}
#endif
