// generated by the clcli. DO NOT EDIT!

#include <columns.h>

#include "messages.h"

#ifdef __cplusplus
extern "C" {
#endif

// line messages.h:3:8
static const clColumn stUseItemReqColumns[] = {
    DEFINE_COLUMN_NUMBER(struct stUseItemReq, itemID),
};
const clColumn stUseItemReqObject[] = {
    DEFINE_OBJECT(struct stUseItemReq, stUseItemReqColumns),
};

// line messages.h:8:8
static const clColumn stDropColumns[] = {
    DEFINE_COLUMN_NUMBER(struct stDrop, itemID),
    DEFINE_COLUMN_NUMBER(struct stDrop, itemNum),
};
const clColumn stDropObject[] = {
    DEFINE_OBJECT(struct stDrop, stDropColumns),
};

// line messages.h:14:8
static const clColumn stUseItemRspColumns[] = {
    DEFINE_COLUMN_NUMBER(struct stUseItemRsp, code),
    DEFINE_COLUMN_NUMBER(struct stUseItemRsp, num),
    DEFINE_COLUMN_OBJECT_FLEXIBLE_ARRAY(struct stUseItemRsp, drops, stDropObject),
};
const clColumn stUseItemRspObject[] = {
    DEFINE_OBJECT(struct stUseItemRsp, stUseItemRspColumns),
};

#ifdef __cplusplus
}
#endif
