#pragma once

// generated by the columns. DO NOT EDIT!


#ifdef __cplusplus
extern "C" {
#endif
struct clColumn;

extern const struct clColumn stFuzzObject[];
extern const struct clColumn stTestsObject[];
#ifdef __cplusplus
}
#endif
