// generated by the columns. DO NOT EDIT!

#include "messages.h"

#define USE_COLUMN_MACROS
#include <columns.h>

#ifdef __cplusplus
extern "C" {
#endif

// messages.h:3:7
static const clColumn stValueColumns[] = {
    DEFINE_COLUMN_NUMBER(union stValue, i32),
    DEFINE_COLUMN_NUMBER(union stValue, u32),
    DEFINE_COLUMN_NUMBER(union stValue, c),
    DEFINE_COLUMN_NUMBER(union stValue, u8),
    DEFINE_COLUMN_FIXED_ARRAY(union stValue, other),
};
// messages.h:13:8
static const clColumn stFuzzColumns[] = {
    DEFINE_COLUMN_FIXED_ARRAY(struct stFuzz, name),
    DEFINE_COLUMN_NUMBER(struct stFuzz, tag),
    DEFINE_COLUMN_UNION(struct stFuzz, v, stValueColumns),
};
const clColumn stFuzzObject[] = {
    DEFINE_OBJECT(struct stFuzz, stFuzzColumns),
};

// messages.h:19:8
static const clColumn stTestsColumns[] = {
    DEFINE_COLUMN_NUMBER(struct stTests, epoch),
    DEFINE_COLUMN_NUMBER(struct stTests, len),
    DEFINE_COLUMN_FLEXIBLE_ARRAY(struct stTests, name),
    DEFINE_COLUMN_NUMBER(struct stTests, fuzzNum),
    DEFINE_COLUMN_OBJECT_FLEXIBLE_ARRAY(struct stTests, fuzz, stFuzzObject),
};
const clColumn stTestsObject[] = {
    DEFINE_OBJECT(struct stTests, stTestsColumns),
};
#ifdef __cplusplus
}
#endif
